# NumPy 学习教程

欢迎来到NumPy学习教程！本教程将按照循序渐进的方式，带你掌握NumPy的核心概念和技能。

## 学习目标
- 理解NumPy的基础概念和优势
- 掌握数组的创建和操作方法
- 学会使用NumPy进行数学运算
- 理解广播机制和数组变形
- 能够应用NumPy解决实际问题

## 学习建议
1. **动手实践**：每个代码块都要亲自编写和运行
2. **理解原理**：不仅要会用，还要理解为什么
3. **循序渐进**：确保每个章节都掌握后再进入下一章节
4. **多做练习**：尝试用学到的知识解决实际问题

## 第1章：NumPy基础概念

### 学习目标
- 了解什么是NumPy及其重要性
- 掌握NumPy的安装和导入方法
- 理解NumPy与Python列表的区别

### 重要概念
- **NumPy**：Python中用于科学计算的核心库
- **ndarray**：NumPy的多维数组对象
- **向量化操作**：对整个数组进行操作，无需循环
- **性能优势**：比Python列表更快的运算速度

In [6]:
! pip install numpy
! pip install pyyaml

In [7]:
# 任务1：导入NumPy库并检查版本
# 要求：
# 1. 导入numpy库，使用别名np
import numpy as np
# 2. 打印NumPy的版本信息
print(f"Numpy版本: {np.__version__}")
# 3. 打印NumPy的配置信息
np.show_config()
print("-" * 50)
np.__config__
print("-" * 50)
np.get_printoptions()
print("-" * 50)


Numpy版本: 2.0.2
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-vclkdodh/cp39-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-vclkdodh/cp39-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=24
    pc file directory: D:/a/numpy/numpy/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-vclkdodh/cp39-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-vclkdodh/cp39-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3

In [ ]:
# 任务2：理解NumPy数组与Python列表的区别
# 要求：
# 1. 创建一个Python列表，包含数字1-5
arr = [i for i in range(1, 6)]
print(f"数组arr: {arr}, 类型: {type(arr)}")
# 2. 创建一个NumPy数组，包含相同的数字
arr_np = np.array([i for i in range(1, 6)])
print(f"数组arr_np: {arr_np}, 类型: {type(arr_np)}")
# 3. 对列表和数组分别进行乘法运算，观察区别
arr_mult = arr * 2
print(f"列表arr乘以2的结果: {arr_mult}, 类型: {type(arr_mult)}")
arr_np_mult = arr_np * 2
print(f"数组arr_np乘以2的结果: {arr_np_mult}, 类型: {type(arr_np_mult)}")


数组arr: [1, 2, 3, 4, 5], 类型: <class 'list'>
数组arr_np: [1 2 3 4 5], 类型: <class 'numpy.ndarray'>
列表arr乘以2的结果: [1, 2, 3, 4, 5, 1, 2, 3, 4, 5], 类型: <class 'list'>
数组arr_np乘以2的结果: [ 2  4  6  8 10], 类型: <class 'numpy.ndarray'>


## 第2章：数组创建

### 学习目标
- 掌握各种创建NumPy数组的方法
- 理解不同创建方法的适用场景
- 学会创建特殊类型的数组

### 核心方法
- `np.array()`：从列表创建数组
- `np.zeros()`：创建全零数组
- `np.ones()`：创建全一数组
- `np.arange()`：创建等差数列
- `np.linspace()`：创建等间距数列
- `np.random.random()`：创建随机数组

In [33]:
# 任务3：从列表创建数组
# 要求：
# 1. 从一维列表[1,2,3,4,5]创建数组
arr_1d = np.array([1, 2, 3, 4, 5])
print(f"一维数组: \n {arr_1d}")
print(f"形状: {arr_1d.shape}")
print(f"维度: {arr_1d.ndim}")
print("-" * 50)
# 2.1 从二维列表[[1,2,3],[4,5,6]]创建数组
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(f"二维数组: \n{arr_2d}")
print(f"形状: {arr_2d.shape}")
print(f"维度: {arr_2d.ndim}")
# 2.2 查看二维数组的行数和列数
rows, cols = arr_2d.shape
print(f"二维数组的行数: {rows}")
print(f"二维数组的列数: {cols}")
# 2.3 访问二维数组中的元素，例如访问第1行第2列的元素
element = arr_2d[0, 1]
print(f"二维数组中第1行第2列的元素: {element}")
# 2.4 访问二维数组的第一行
first_row = arr_2d[0, :]
print(f"二维数组的第一行: {first_row}")
print("-" * 50)
# 3.1 从三维列表创建一个2x2x2的数组
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(f"三维数组: \n{arr_3d}")
print(f"形状: {arr_3d.shape}")
print(f"维度: {arr_3d.ndim}")
# 3.2 访问三维数组中的元素，例如访问第1层第2行第1列的元素
element_3d = arr_3d[0, 1, 0]
print(f"三维数组中第1层第2行第1列的元素: {element_3d}")
# 3.3 访问三维数组的第一层
first_layer = arr_3d[0, :, :]
print(f"三维数组的第一层: \n{first_layer}")
print("-" * 50)


一维数组: 
 [1 2 3 4 5]
形状: (5,)
维度: 1
--------------------------------------------------
二维数组: 
[[1 2 3]
 [4 5 6]]
形状: (2, 3)
维度: 2
二维数组的行数: 2
二维数组的列数: 3
二维数组中第1行第2列的元素: 2
二维数组的第一行: [1 2 3]
--------------------------------------------------
三维数组: 
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
形状: (2, 2, 2)
维度: 3
三维数组中第1层第2行第1列的元素: 3
三维数组的第一层: 
[[1 2]
 [3 4]]
--------------------------------------------------


In [ ]:
# 任务4：创建特殊数组
# 要求：
# 1. 创建一个3x4的全零数组
arr_zeros = np.zeros((3, 4))
print(f"3x4的全零数组:\n{arr_zeros}")
print("-" * 50)
# 2. 创建一个2x3的全一数组
arr_ones = np.ones((2, 3))
print(f"2x3的全一数组:\n{arr_ones}")
print("-" * 50)
# 3.1 创建一个3x3的单位矩阵
arr_eye = np.eye(3)
print(f"3x3的单位矩阵:\n{arr_eye}")
# 3.2 上2维对角线为1的矩阵
arr_eye_up = np.eye(3, k=2)  # k=1表示上对角线，k=-1表示下对角线
print(f"3x3的上对角线单位矩阵:\n{arr_eye_up}")
# 3.3 非方阵的单位矩阵
arr_eye_non_square = np.eye(2, 3)
print(f"2x3的非方阵单位矩阵:\n{arr_eye_non_square}")
print("-" * 50)
# 4. 创建一个2x2的填充7的数组
arr_full = np.full((2, 2), 7)
print(f"2x2的填充7的数组:\n{arr_full}")

3x4的全零数组:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
--------------------------------------------------
2x3的全一数组:
[[1. 1. 1.]
 [1. 1. 1.]]
--------------------------------------------------
3x3的单位矩阵:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
3x3的上对角线单位矩阵:
[[0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]
2x3的非方阵单位矩阵:
[[1. 0. 0.]
 [0. 1. 0.]]
--------------------------------------------------
2x2的填充7的数组:
[[7 7]
 [7 7]]


In [ ]:
# 任务5：创建序列数组
# 要求：
# 1.1 使用arange创建1-10的数组，步长为2
arr_arange = np.arange(1, 11, 2)
print(f"使用arange创建的数组(0-10, 步长2): \n {arr_arange}")
print(f"类型: {type(arr_arange)}")
print("-" * 50)
# 2. 使用arange创建10-1的递减数组
arr_arange_dec = np.arange(10, 0, -1)
print(f"使用arange创建的递减数组(10-0): \n {arr_arange_dec}")
# 3. 使用linspace创建0-1之间的5个等间距数
arr_linspace_0_1 = np.linspace(0, 1, 5)
print(f"使用linspace创建的数组(0-1之间的5个等间距数): \n {arr_linspace_0_1}")
print(f"类型: {type(arr_linspace_0_1)}")
print("-" * 50)
# 4. 使用linspace创建0-2π之间的10个等间距数
arr_linspace_0_2pi = np.linspace(0, 2 * np.pi, 10)
print(f"使用linspace创建的数组(0-2π之间的10个等间距数): \n {arr_linspace_0_2pi}")


使用arange创建的数组(0-10, 步长2): 
 [1 3 5 7 9]
类型: <class 'numpy.ndarray'>
--------------------------------------------------
使用arange创建的递减数组(10-0): 
 [10  9  8  7  6  5  4  3  2  1]
使用linspace创建的数组(0-1之间的5个等间距数): 
 [0.   0.25 0.5  0.75 1.  ]
类型: <class 'numpy.ndarray'>
--------------------------------------------------
使用linspace创建的数组(0-2π之间的10个等间距数): 
 [0.        0.6981317 1.3962634 2.0943952 2.7925267 3.4906585 4.1887903
 4.886922  5.5850534 6.2831855]


In [113]:
# 任务6：创建随机数组
# 要求：
# 1. 创建一个2x3的随机数组（0-1之间）
arr_random_rand = np.random.rand(2, 3)
arr_random_random = np.random.random(size=(2, 3))
print(f"2x3的随机数组(0-1之间), 使用rand: \n {arr_random_rand}")
print(f"2x3的随机数组(0-1之间), 使用random: \n {arr_random_random}")
print("-" * 50)
# 2. 创建一个3x3的随机整数数组（0-10之间）
arr_random_int = np.random.randint(0, 10, (3, 3))
print(f"3x3的随机整数数组(0-10之间): \n {arr_random_int}")
print("-" * 50)
# 3. 创建一个符合正态分布的随机数组（均值0，标准差1）
arr_random_randn = np.random.randn(10)
average_arr = arr_random_randn.sum() / arr_random_randn.shape[0]
std_arr = arr_random_randn.std()
print(f"1维符合正态分布的随机数组: \n{arr_random_randn}")
print(f"数组的平均值: {average_arr}")
print(f"数组的标准差: {std_arr}")
# 4. 设置随机种子为42，然后创建一个2x2的随机数组
np.random.seed(42)
arr_random_seed_1 = np.random.random(size=(2, 2))
np.random.seed(42)
arr_random_seed_2 = np.random.random(size=(2, 2))
print(f"两个数组每个元素是否相同: {arr_random_seed_1 == arr_random_seed_2}")
print(f"两个数组是否相同: {np.array_equal(arr_random_seed_1, arr_random_seed_2)}")

2x3的随机数组(0-1之间), 使用rand: 
 [[0.15601864 0.15599452 0.05808361]
 [0.86617615 0.60111501 0.70807258]]
2x3的随机数组(0-1之间), 使用random: 
 [[0.02058449 0.96990985 0.83244264]
 [0.21233911 0.18182497 0.18340451]]
--------------------------------------------------
3x3的随机整数数组(0-10之间): 
 [[9 5 8]
 [0 9 2]
 [6 3 8]]
--------------------------------------------------
1维符合正态分布的随机数组: 
[ 0.12221917 -0.51543566 -0.60025385  0.94743982  0.291034   -0.63555974
 -1.02155219 -0.16175539 -0.5336488  -0.00552786]
数组的平均值: -0.21130405121772355
数组的标准差: 0.5417791609589815
两个数组每个元素是否相同: [[ True  True]
 [ True  True]]
两个数组是否相同: True


## 第3章：数组属性

### 学习目标
- 掌握NumPy数组的重要属性
- 理解数组形状、维度、数据类型等概念
- 学会查看和修改数组属性

### 重要属性
- `shape`：数组的形状
- `ndim`：数组的维度
- `size`：数组的元素总数
- `dtype`：数组的数据类型
- `itemsize`：每个元素的大小（字节）
- `nbytes`：数组的总大小（字节）

In [126]:
# 任务7：探索数组属性
# 要求：
# 1. 创建一个3x4的二维数组
arr = np.random.random(size=(3, 4))
print(f"数组为: \n {arr}")
# 2. 打印该数组的所有属性（shape, ndim, size, dtype, itemsize, nbytes）
print(f"数组的形状shape为: {arr.shape}")
print(f"数组的维度ndim为: {arr.ndim}")
print(f"数组的元素总数size: {arr.size}")
print(f"数组中数据类型dtype: {arr.dtype}")
print(f"数组中每个元素的大小itemsize: {arr.itemsize}")
print(f"数组总大小nbytes(字节): {arr.nbytes}")
# 3. 创建一个一维数组，包含10个元素
arr_1d = np.linspace(0, 1, 10)
print(f"1维10数据数组: \n{arr_1d}")
# 4. 比较两个数组的属性差异

# 在这里编写你的代码：


数组为: 
 [[0.05147875 0.27864646 0.90826589 0.23956189]
 [0.14489487 0.48945276 0.98565045 0.24205527]
 [0.67213555 0.76161962 0.23763754 0.72821635]]
数组的形状shape为: (3, 4)
数组的维度ndim为: 2
数组的元素总数size: 12
数组中数据类型dtype: float64
数组中每个元素的大小itemsize: 8
数组总大小nbytes(字节): 96
1维10数据数组: 
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [ ]:
# 任务8：数据类型操作
# 要求：
# 1. 创建一个整数数组，指定数据类型为np.int8
arr_int = np.linspace(start=1, stop=11, num=10, dtype=np.int8)
print(f"数据类型位int的数组为: \n{arr_int}")
# 2. 创建一个浮点数数组，指定数据类型为np.float16
arr_float = np.linspace(start=0, stop=1, num=10, dtype=np.float16)
print(f"数据类型位float的数组为: \n{arr_float}")
# 3. 创建一个布尔数组
arr_bool = arr_int > 5
print(f"如果arr_int中的值大于5就为True, 得到布尔数组: \n{arr_bool}")
# 4. 尝试改变数组的数据类型
arr_float_to_int = arr_float.astype(np.int8)
print(f"把np.float16类型改成np.int8类型: \n {arr_float_to_int}")
print(f"数据类型为: {arr_float_to_int.dtype}")


数据类型位int的数组为: 
[ 1  2  3  4  5  6  7  8  9 11]
数据类型位float的数组为: 
[0.     0.1111 0.2222 0.3333 0.4443 0.5557 0.6665 0.778  0.8887 1.    ]
如果arr_int中的值大于5就为True, 得到布尔数组: 
[False False False False False  True  True  True  True  True]
把np.float16类型改成np.int8类型: 
 [0 0 0 0 0 0 0 0 0 1]
数据类型为: int8


## 第4章：数组索引和切片

### 学习目标
- 掌握NumPy数组的基本索引方法
- 学会使用切片操作访问数组元素
- 理解布尔索引和花式索引

### 核心概念
- **基本索引**：使用整数索引访问元素
- **切片**：使用冒号语法访问子数组
- **布尔索引**：使用布尔条件选择元素
- **花式索引**：使用整数数组选择元素

In [ ]:
# 任务9：基本索引操作
# 要求：
# 1. 创建一个3x4的二维数组
arr = np.random.random(size=(3, 4))
print(f"数组为: \n{arr}")
# 2. 访问第一行的所有元素
arr_row1 = arr[0, :]
print(f"第一行所有元素为: \n{arr_row1}")
# 3. 访问第二列的所有元素
arr_col2 = arr[:, 1]
print(f"第二列所有元素: \n{arr_col2}")
# 4. 访问第二行第三列的元素
arr_row2_col3 = arr[1, 2]
print(f"第二行第三列元素: \n{arr_row2_col3}")
# 5. 访问最后一个元素
arr_last = arr[-1, -1]
print(f"最后一个元素: {arr_last}")

数组为: 
[[0.25794163 0.65998405 0.8172222  0.55520081]
 [0.52965058 0.24185229 0.09310277 0.89721576]
 [0.90041806 0.63310146 0.33902979 0.34920957]]
第一行所有元素为: 
[0.25794163 0.65998405 0.8172222  0.55520081]
第二列所有元素: 
[0.65998405 0.24185229 0.63310146]
第二行第三列元素: 
0.09310276780589921
最后一个元素: 0.3492095746126609


In [155]:
# 任务10：切片操作
# 要求：
# 1. 创建一个包含0-15的一维数组
arr = np.arange(start=0, stop=16, step=1)
print(f"数组为: \n {arr}")
# 2. 获取前5个元素
arr_first5 = arr[0:5]
print(f"前5个元素为: {arr_first5}")
# 3. 获取第3到第8个元素
arr_3_to_8 = arr[2:8]
print(f"获取第3到第8个元素: {arr_3_to_8}")
# 4. 获取从第2个开始，每隔2个元素
arr_2_to_last = arr[2::2]
print(arr_2_to_last)
# 5. 将数组反转
print(f"反转数组: {arr[::-1]}")
# 在这里编写你的代码：


数组为: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
前5个元素为: [0 1 2 3 4]
获取第3到第8个元素: [2 3 4 5 6 7]
[ 2  4  6  8 10 12 14]
反转数组: [15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


In [ ]:
# 任务11：多维数组切片
# 要求：
# 1. 创建一个4x5的二维数组
arr = np.random.random(size=(4, 5))
print(f"创建数组: \n{arr}")
# 2. 获取前两行的所有列
arr_col0to1 = arr[0:2, ]
print(f"前两行的数组: \n {arr_col0to1}")
# 3. 获取所有行的第2-4列

# 4. 获取第2-3行的第1-3列
# 5. 获取每隔一行的每隔一列

# 在这里编写你的代码：


创建数组: 
[[0.3253997  0.74649141 0.6496329  0.84922341 0.65761289]
 [0.5683086  0.09367477 0.3677158  0.26520237 0.24398964]
 [0.97301055 0.39309772 0.89204656 0.63113863 0.7948113 ]
 [0.50263709 0.57690388 0.49251769 0.19524299 0.72245212]]
前两行的数组: 
 [[0.3253997  0.74649141 0.6496329  0.84922341 0.65761289]
 [0.5683086  0.09367477 0.3677158  0.26520237 0.24398964]]


In [169]:
# 任务12：布尔索引
# 要求：
# 1. 创建一个包含0-20的数组
arr = np.arange(0, 21, step=1)
print(f"0-20的数组: \n {arr}")
# 2. 选择所有大于10的元素
arr_geq_10 = arr[arr > 10]
print(f"所有大于10的元素: \n{arr_geq_10}")
# 3. 选择所有偶数
arr_odds = arr[arr % 2 == 0]
print(f"偶数数组: \n{arr_odds}")
# 4. 选择所有在5-15之间的元素
arr_5_to_15 = arr[(arr >= 5) & (arr <= 15)]
print(f"5-15的所有元素: \n{arr_5_to_15}")
# 5. 选择所有能被3整除的元素
arr_mod3 = arr[arr % 3 == 0]
print(f"可以被3整除的数组: \n{arr_mod3}")

0-20的数组: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
所有大于10的元素: 
[11 12 13 14 15 16 17 18 19 20]
偶数数组: 
[ 0  2  4  6  8 10 12 14 16 18 20]
5-15的所有元素: 
[ 5  6  7  8  9 10 11 12 13 14 15]
可以被3整除的数组: 
[ 0  3  6  9 12 15 18]


## 第5章：数组运算

### 学习目标
- 掌握NumPy数组的基本数学运算
- 理解向量化操作的优势
- 学会使用比较运算和逻辑运算

### 运算类型
- **算术运算**：加减乘除、幂运算
- **比较运算**：大于、小于、等于等
- **逻辑运算**：与、或、非
- **统计运算**：求和、均值、标准差等

In [ ]:
# 任务13：基本算术运算
# 要求：
# 1. 创建两个数组a=[1,2,3,4], b=[5,6,7,8]
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
# 2. 计算两个数组的加、减、乘、除
print(f"加法: {a + b}")
print(f"减法: {a - b}")
print(f"乘法: {a * b}")
print(f"除法: {a / b}")
# 3. 计算数组a的平方
print(f"a的平方:{a**2}")
# 4. 计算数组a的平方根
print(f"a的平方根: {a**0.5}")

加法: [ 6  8 10 12]
减法: [-4 -4 -4 -4]
乘法: [ 5 12 21 32]
除法: [0.2        0.33333333 0.42857143 0.5       ]
a的平方:[ 1  4  9 16]
a的平方根: [1.         1.41421356 1.73205081 2.        ]


In [ ]:
# 任务14：比较运算
# 要求：
# 1. 创建两个数组a=[1,2,3,4], b=[4,3,2,1]
a = np.array([1, 2, 3, 4])
b = np.array([4, 3, 2, 1])
# 2. 比较两个数组的元素是否相同
print(f"数组的每个元素是否相同: {a == b}")

数组的每个元素是否相同: [False False False False]


In [ ]:
# 任务15：统计运算
# 要求：
# 1. 创建一个包含1-10的数组
arr = np.random.randint(low=1, high=10, size=(5,))
print(f"数组为:\n {arr}")
# 2. 计算数组的和、均值、标准差、方差
print(f"和为:{arr.sum()}")
print(f"均值为: {arr.mean()}")
print(f"标准差为: {arr.std()}")
print(f"方差为: {arr.var()}")
# 3. 找出数组的最小值、最大值及其索引
print(f"数组最小值为:{arr.min()}, 索引为{arr.argmin()}")
print(f"数组最大值为: {arr.max()}, 索引为{arr.argmax()}")
# 4. 计算数组的累积和和累积积
print(f"累积和: {arr.cumsum()}")
print(f"累积积: {arr.cumprod()}")

数组为:
 [2 2 7 6 3]
和为:20
均值为: 4.0
标准差为: 2.0976176963403033
方差为: 4.4
数组最小值为:2, 索引为0
数组最大值为: 7, 索引为2
累积和: [ 2  4 11 17 20]
累积积: [  2   4  28 168 504]


## 第6章：线性代数运算

### 学习目标
- 掌握NumPy中的线性代数运算
- 理解矩阵运算的概念
- 学会使用NumPy的线性代数函数

### 重要函数
- `np.dot()`：矩阵乘法
- `np.matmul()`：矩阵乘法
- `np.linalg.inv()`：矩阵求逆
- `np.linalg.det()`：行列式
- `np.linalg.eig()`：特征值和特征向量

In [ ]:
# 任务16：矩阵乘法
# 要求：
# 1. 创建两个2x3和3x2的矩阵
# 2. 使用np.dot()计算矩阵乘法
# 3. 使用@运算符计算矩阵乘法
# 4. 比较两种方法的结果

# 在这里编写你的代码：


In [ ]:
# 任务17：矩阵运算
# 要求：
# 1. 创建一个2x2的矩阵
# 2. 计算矩阵的行列式
# 3. 计算矩阵的逆矩阵
# 4. 计算矩阵的特征值和特征向量
# 5. 验证矩阵与其逆矩阵的乘积是否为单位矩阵

# 在这里编写你的代码：


## 第7章：数组变形

### 学习目标
- 掌握NumPy数组的变形方法
- 学会改变数组的形状和维度
- 理解数组转置和轴变换

### 核心方法
- `reshape()`：改变数组形状
- `flatten()`：将数组展平为一维
- `ravel()`：将数组展平为一维（返回视图）
- `transpose()`：数组转置
- `T`：转置属性

In [ ]:
# 任务18：数组变形
# 要求：
# 1. 创建一个包含1-12的数组
# 2. 将其变形为3x4的数组
# 3. 将其变形为2x6的数组
# 4. 将其变形为4x3的数组
# 5. 尝试变形为不可能的形状，观察错误

# 在这里编写你的代码：


In [ ]:
# 任务19：数组展平
# 要求：
# 1. 创建一个3x4的二维数组
# 2. 使用flatten()将其展平为一维数组
# 3. 使用ravel()将其展平为一维数组
# 4. 比较两种方法的区别（修改原数组后观察）

# 在这里编写你的代码：


In [ ]:
# 任务20：数组转置
# 要求：
# 1. 创建一个3x4的二维数组
# 2. 使用T属性进行转置
# 3. 使用transpose()函数进行转置
# 4. 创建一个3x4x5的三维数组，进行轴变换

# 在这里编写你的代码：


## 第8章：广播机制

### 学习目标
- 理解NumPy的广播机制
- 掌握广播的规则和原理
- 学会利用广播进行高效运算

### 广播规则
1. 从后向前比较每个维度的尺寸
2. 维度尺寸相同或其中一个为1时可以广播
3. 缺失的维度可以广播
4. 广播后会扩展到最大的形状

In [ ]:
# 任务21：标量与数组广播
# 要求：
# 1. 创建一个3x3的数组
# 2. 将数组与标量5进行加法运算
# 3. 将数组与标量2进行乘法运算
# 4. 观察广播的结果和原理

# 在这里编写你的代码：


In [ ]:
# 任务22：不同形状数组广播
# 要求：
# 1. 创建一个3x3的数组A
# 2. 创建一个1x3的数组B
# 3. 创建一个3x1的数组C
# 4. 进行A+B、A+C的运算，观察广播效果
# 5. 尝试不能广播的形状组合

# 在这里编写你的代码：


## 第9章：数组连接和分割

### 学习目标
- 掌握NumPy数组的连接方法
- 学会分割数组
- 理解不同轴的连接和分割

### 重要函数
- `np.concatenate()`：连接数组
- `np.stack()`：堆叠数组
- `np.hstack()`：水平连接
- `np.vstack()`：垂直连接
- `np.split()`：分割数组

In [ ]:
# 任务23：数组连接
# 要求：
# 1. 创建两个3x3的数组A和B
# 2. 使用concatenate沿轴0连接（垂直连接）
# 3. 使用concatenate沿轴1连接（水平连接）
# 4. 使用vstack和hstack进行连接
# 5. 比较不同连接方法的结果

# 在这里编写你的代码：


In [ ]:
# 任务24：数组堆叠
# 要求：
# 1. 创建两个3x3的数组A和B
# 2. 使用stack沿新轴堆叠
# 3. 使用vstack和hstack堆叠
# 4. 使用dstack沿深度方向堆叠
# 5. 观察不同堆叠方式的维度变化

# 在这里编写你的代码：


In [ ]:
# 任务25：数组分割
# 要求：
# 1. 创建一个包含0-11的数组，变形为3x4
# 2. 使用split沿轴0分割成3个子数组
# 3. 使用split沿轴1分割成2个子数组
# 4. 使用hsplit和vsplit进行分割
# 5. 尝试不均匀分割

# 在这里编写你的代码：


## 第10章：文件操作

### 学习目标
- 掌握NumPy数组的保存和加载方法
- 学会读写文本文件
- 理解不同文件格式的特点

### 重要函数
- `np.save()`：保存数组为.npy文件
- `np.load()`：加载.npy文件
- `np.savetxt()`：保存数组为文本文件
- `np.loadtxt()`：加载文本文件

In [ ]:
# 任务26：保存和加载二进制文件
# 要求：
# 1. 创建一个3x3的随机数组
# 2. 使用np.save()保存为.npy文件
# 3. 使用np.load()加载保存的文件
# 4. 验证加载的数组与原数组是否相同

# 在这里编写你的代码：


In [ ]:
# 任务27：保存和加载文本文件
# 要求：
# 1. 创建一个3x3的数组
# 2. 使用np.savetxt()保存为.txt文件
# 3. 使用np.loadtxt()加载文本文件
# 4. 尝试指定不同的分隔符和格式

# 在这里编写你的代码：


## 第11章：实用函数

### 学习目标
- 掌握NumPy的实用函数
- 学会排序和搜索操作
- 理解集合操作

### 重要函数
- `np.sort()`：排序数组
- `np.argsort()`：返回排序索引
- `np.unique()`：找出唯一值
- `np.intersect1d()`：交集
- `np.union1d()`：并集

In [ ]:
# 任务28：排序操作
# 要求：
# 1. 创建一个包含随机数的数组
# 2. 使用np.sort()进行排序
# 3. 使用np.argsort()获取排序索引
# 4. 对二维数组沿不同轴进行排序

# 在这里编写你的代码：


In [ ]:
# 任务29：唯一值和集合操作
# 要求：
# 1. 创建一个包含重复元素的数组
# 2. 使用np.unique()找出唯一值
# 3. 创建两个数组，计算它们的交集
# 4. 计算两个数组的并集和差集

# 在这里编写你的代码：


## 第12章：综合实战

### 学习目标
- 综合运用所学的NumPy知识
- 解决实际问题
- 提高编程能力

### 实战项目
1. **数据分析**：使用NumPy处理和分析数据
2. **算法实现**：用NumPy实现简单算法
3. **性能优化**：比较NumPy和Python循环的性能

In [ ]:
# 任务30：数据分析实战
# 要求：
# 1. 创建一个包含学生成绩的数组（5个学生，3门课程）
# 2. 计算每个学生的总分和平均分
# 3. 计算每门课程的平均分和标准差
# 4. 找出每门课程的最高分和最低分
# 5. 对学生按总分进行排序

# 在这里编写你的代码：


In [ ]:
# 任务31：线性回归实现
# 要求：
# 1. 创建一些线性数据（y = 2x + 1 + 噪声）
# 2. 使用NumPy实现最小二乘法
# 3. 计算斜率和截距
# 4. 预测新的x值对应的y值
# 5. 计算预测误差

# 在这里编写你的代码：


In [ ]:
# 任务32：性能对比
# 要求：
# 1. 创建一个包含100万个元素的数组
# 2. 使用NumPy向量化操作计算所有元素的平方
# 3. 使用Python循环计算相同操作
# 4. 比较两种方法的执行时间
# 5. 分析性能差异的原因

# 在这里编写你的代码：


## 总结

恭喜你完成了NumPy学习教程！通过本教程，你已经掌握了：

### 核心技能
- ✅ NumPy基础概念和数组创建
- ✅ 数组属性和索引切片
- ✅ 数组运算和数学函数
- ✅ 线性代数运算
- ✅ 数组变形和广播机制
- ✅ 数组连接和分割
- ✅ 文件操作和实用函数
- ✅ 综合实战应用

### 下一步学习
现在你已经掌握了NumPy的基础，可以继续学习：
1. **Pandas**：基于NumPy的数据分析库
2. **Matplotlib**：数据可视化库
3. **Scikit-learn**：机器学习库
4. **深度学习框架**：TensorFlow、PyTorch等

### 学习建议
- **持续练习**：NumPy需要大量练习才能熟练掌握
- **实际应用**：在实际项目中使用NumPy
- **深入学习**：探索NumPy的高级功能
- **社区参与**：参与NumPy社区，学习最佳实践

祝你在机器学习的道路上越走越远！